### ISSUE TITLE
Un peu d'aide ? :)

### ISSUE THREAD

**Issue by locness3** [octocody/octocody.github.io#1]
Je vois que tu galères un peu, donc je vais t'aider :)

Tout le contenu (les porjets) est stocké dans le dossier `_stuff` sous forme de fichiers Markdown.

Ce que je te conseille de faire c'est de copier un fichier existant puis de remplacer le contenu.

Dans les fichiers :

- `title` est le **titre du projet**, par exemple `Scratch profile Embed`
- `date`, en théorie c'est la date. En fait tu peux l'utiliser pour changer l'ordre de l'affichage des projets (ils sont affichés du plus vieux au plus anicen). Fais attention au **formatage** de la date, ou le contenu pourrait ne pas apparaître.
- `image` correspond à **l'image affichée en fond** pour le projet. Mets-les dans le dossier `uploads`, puis référence-les ici.
- `link` correspond à **la page qui s'affiche si tu cliques sur le bouton** du projet (voir ci-dessous)
- Et `link-title` corrspond au **texte afrfiché sur le bouton** du projet.

Au fait, tu peux supprimer le fichier inutile `bib-man-manifest.json` et le dossier `.forestry`.

Dernière chose, j’apprécierai que tu me cite quelque part sur le site ou dans le README.

J'espère t'avoir été utile 😄

**Comment by locness3** [comment]
@octocody

**Comment by octocody** [comment]
Thx men
